import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { authorize, audit } from "@/lib/guard";
import { generateUniqueOrderShortId } from "@/lib/shortId";
import { activeBranch, activeBranchId } from "@/lib/branchScope";
import { isPaymentMethod } from "@/lib/paymentMethods";
import { applyLoyalty, LoyaltyError } from "@/lib/loyalty";

// POST /api/orders — place a new order (POS).
export async function POST(req: Request) {
  const guard = await authorize("pos.use");
  if (!guard.ok) return guard.response;
  const branch = await activeBranch(guard.session);
  const branchId = await activeBranchId(guard.session);

  const body = await req.json().catch(() => ({}));
  const pagerNumber = Number(body.pagerNumber);
  const paymentMethod = body.paymentMethod;
  // Default "walk_in" for backward compatibility with any old clients that don't send it.
  const orderType = body.orderType === "takeaway" ? "takeaway" : "walk_in";
  const isPaid = typeof body.isPaid === "boolean" ? body.isPaid : true;
  const items = Array.isArray(body.items) ? body.items : [];
  // Offline idempotency key (UUID) generated by the cashier tablet. Optional — online
  // orders may omit it; capped at 64 chars to bound storage.
  const clientId =
    typeof body.clientId === "string" && body.clientId.length > 0
      ? body.clientId.slice(0, 64)
      : null;

  // Idempotent retry: if this clientId already produced an order (the network dropped
  // after we created it but before the response reached the tablet), return that order
  // instead of creating a duplicate. This MUST run before the pager-in-use check —
  // otherwise the retry would 409 on the very pager its own order is holding.
  if (clientId) {
    const existing = await prisma.order.findUnique({
      where: { clientId },
      include: { items: true },
    });
    if (existing) return NextResponse.json({ order: existing }, { status: 200 });
  }

  if (!Number.isInteger(pagerNumber) || pagerNumber < 1 || pagerNumber > 30)
    return NextResponse.json({ error: "Pager number must be between 1 and 30" }, { status: 400 });
  if (!isPaymentMethod(paymentMethod))
    return NextResponse.json({ error: "Payment method must be cash, card, or pos" }, { status: 400 });
  if (items.length === 0)
    return NextResponse.json({ error: "Add at least one item" }, { status: 400 });

  // Reject if this pager is already in use by an uncollected order at THIS
  // physical branch (each branch has its own physical pager set — Sulaymaniyah's
  // two branches can use the same pager number at once).
  const inUse = await prisma.order.findFirst({
    where: { branchId, pagerNumber, status: { in: ["pending", "ready"] } },
  });
  if (inUse)
    return NextResponse.json(
      { error: `Pager ${pagerNumber} is already in use` },
      { status: 409 }
    );

  // Build line items and compute the gross total server-side (never trust the
  // client total). The loyalty discount/redemption (if any) is deducted below.
  const lineItems = items.map(
    (i: { name: string; price: number; quantity: number; modifier?: string | null }) => ({
      name: String(i.name),
      price: Math.round(Number(i.price)),
      quantity: Math.max(1, Math.round(Number(i.quantity))),
      modifier: i.modifier ? String(i.modifier) : null,
    })
  );
  const grossTotal = lineItems.reduce(
    (s: number, i: { price: number; quantity: number }) => s + i.price * i.quantity,
    0
  );

  // Unique human-facing code, generated + collision-checked at creation time.
  const shortId = await generateUniqueOrderShortId(prisma);

  // An event tag must belong to the same branch.
  if (body.eventId) {
    const ev = await prisma.event.findFirst({ where: { id: String(body.eventId), branch } });
    if (!ev) return NextResponse.json({ error: "Event not found" }, { status: 400 });
  }

  const rawPhone = typeof body.customerPhone === "string" ? body.customerPhone : null;
  const redeemFreeItem = body.redeemFreeItem === true;

  // Ad-hoc discount (unrelated to loyalty) — the cashier types this in fresh at
  // checkout for a friend/regular, not stored anywhere per phone/customer.
  const manualDiscountType = body.manualDiscountType === "pct" || body.manualDiscountType === "flat"
    ? body.manualDiscountType
    : null;
  const manualDiscountValue = Math.round(Number(body.manualDiscountValue));
  if (manualDiscountType === "pct" && (!Number.isFinite(manualDiscountValue) || manualDiscountValue <= 0 || manualDiscountValue > 100))
    return NextResponse.json({ error: "Discount percentage must be between 1 and 100" }, { status: 400 });
  if (manualDiscountType === "flat" && (!Number.isFinite(manualDiscountValue) || manualDiscountValue <= 0))
    return NextResponse.json({ error: "Discount amount must be a positive number" }, { status: 400 });

  let order;
  let loyaltyJustQualified = false;
  try {
    order = await prisma.$transaction(async (tx) => {
      const loyalty = await applyLoyalty(tx, { rawPhone, lineItems, redeemFreeItem });
      loyaltyJustQualified = loyalty.justQualified;

      const afterLoyalty = Math.max(0, grossTotal - loyalty.freeItemAmount);
      let manualDiscountAmount = 0;
      let manualDiscountPct: number | null = null;
      if (manualDiscountType === "pct") {
        manualDiscountPct = manualDiscountValue;
        manualDiscountAmount = Math.round(afterLoyalty * (manualDiscountValue / 100));
      } else if (manualDiscountType === "flat") {
        manualDiscountAmount = Math.min(manualDiscountValue, afterLoyalty);
      }
      const discountAmount = loyalty.freeItemAmount + manualDiscountAmount;
      const total = Math.max(0, grossTotal - discountAmount);

      const created = await tx.order.create({
        data: {
          shortId,
          clientId,
          branch,
          branchId,
          pagerNumber,
          paymentMethod,
          orderType,
          isPaid,
          total,
          staffId: guard.session.sub,
          eventId: body.eventId || null, // null = the branch itself (no event)
          items: { create: lineItems },
          customerId: loyalty.customerId,
          customerPhone: loyalty.customerPhone,
          discountPct: manualDiscountPct,
          discountAmount,
        },
        include: { items: true },
      });

      if (loyalty.redeemed && loyalty.customerId) {
        await tx.loyaltyRedemption.create({
          data: {
            customerId: loyalty.customerId,
            orderId: created.id,
            branch,
            staffId: guard.session.sub,
          },
        });
      }

      return created;
    });
  } catch (e) {
    if (e instanceof LoyaltyError) return NextResponse.json({ error: e.message }, { status: 400 });
    throw e;
  }

  const discountNote = order.discountAmount > 0 ? `, discount ${order.discountAmount} IQD` : "";
  await audit(guard.session.sub, `Placed order ${shortId} (#${pagerNumber}, ${order.total} IQD${discountNote})`);
  return NextResponse.json(
    { order, loyaltyStatus: { justQualified: loyaltyJustQualified, phone: order.customerPhone } },
    { status: 201 }
  );
}
