import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { authorize, audit } from "@/lib/guard";
import { generateUniqueOrderShortId } from "@/lib/shortId";
import { activeBranch } from "@/lib/branchScope";

// POST /api/orders — place a new order (POS).
export async function POST(req: Request) {
  const guard = await authorize("pos.use");
  if (!guard.ok) return guard.response;
  const branch = await activeBranch(guard.session);

  const body = await req.json().catch(() => ({}));
  const pagerNumber = Number(body.pagerNumber);
  const paymentMethod = body.paymentMethod;
  // Default "walk_in" for backward compatibility with any old clients that don't send it.
  const orderType = body.orderType === "takeaway" ? "takeaway" : "walk_in";
  const isPaid = typeof body.isPaid === "boolean" ? body.isPaid : true;
  const items = Array.isArray(body.items) ? body.items : [];
  // Offline idempotency key (UUID) generated by the cashier tablet. Optional — online
  // orders may omit it; capped at 64 chars to bound storage.
  const clientId =
    typeof body.clientId === "string" && body.clientId.length > 0
      ? body.clientId.slice(0, 64)
      : null;

  // Idempotent retry: if this clientId already produced an order (the network dropped
  // after we created it but before the response reached the tablet), return that order
  // instead of creating a duplicate. This MUST run before the pager-in-use check —
  // otherwise the retry would 409 on the very pager its own order is holding.
  if (clientId) {
    const existing = await prisma.order.findUnique({
      where: { clientId },
      include: { items: true },
    });
    if (existing) return NextResponse.json({ order: existing }, { status: 200 });
  }

  if (!Number.isInteger(pagerNumber) || pagerNumber < 1 || pagerNumber > 30)
    return NextResponse.json({ error: "Pager number must be between 1 and 30" }, { status: 400 });
  if (paymentMethod !== "cash" && paymentMethod !== "card")
    return NextResponse.json({ error: "Payment method must be cash or card" }, { status: 400 });
  if (items.length === 0)
    return NextResponse.json({ error: "Add at least one item" }, { status: 400 });

  // Reject if this pager is already in use by an uncollected order IN THIS
  // BRANCH (each city has its own physical pager set).
  const inUse = await prisma.order.findFirst({
    where: { branch, pagerNumber, status: { in: ["pending", "ready"] } },
  });
  if (inUse)
    return NextResponse.json(
      { error: `Pager ${pagerNumber} is already in use` },
      { status: 409 }
    );

  // Build line items and compute total server-side (never trust client total).
  const lineItems = items.map(
    (i: { name: string; price: number; quantity: number; modifier?: string | null }) => ({
      name: String(i.name),
      price: Math.round(Number(i.price)),
      quantity: Math.max(1, Math.round(Number(i.quantity))),
      modifier: i.modifier ? String(i.modifier) : null,
    })
  );
  const total = lineItems.reduce(
    (s: number, i: { price: number; quantity: number }) => s + i.price * i.quantity,
    0
  );

  // Unique human-facing code, generated + collision-checked at creation time.
  const shortId = await generateUniqueOrderShortId(prisma);

  // An event tag must belong to the same branch.
  if (body.eventId) {
    const ev = await prisma.event.findFirst({ where: { id: String(body.eventId), branch } });
    if (!ev) return NextResponse.json({ error: "Event not found" }, { status: 400 });
  }

  const order = await prisma.order.create({
    data: {
      shortId,
      clientId,
      branch,
      pagerNumber,
      paymentMethod,
      orderType,
      isPaid,
      total,
      staffId: guard.session.sub,
      eventId: body.eventId || null, // null = the branch itself (no event)
      items: { create: lineItems },
    },
    include: { items: true },
  });

  await audit(guard.session.sub, `Placed order ${shortId} (#${pagerNumber}, ${total} IQD)`);
  return NextResponse.json({ order }, { status: 201 });
}
